definitions:
  errors.Error:
    properties:
      code:
        type: string
      message:
        type: string
      path:
        type: string
      status:
        type: integer
      timestamp:
        type: string
    type: object
  payload.EstimateResponse:
    properties:
      amount:
        type: string
    type: object
info:
  contact: {}
  description: Uniswap API Documentation.
  title: Uniswap API
  version: 0.0.1
paths:
  /estimate:
    get:
      description: Estimate Uniswap V2 pool
      parameters:
      - description: pool
        in: query
        name: pool
        required: true
        type: string
      - description: src
        in: query
        name: src
        required: true
        type: string
      - description: dst
        in: query
        name: dst
        required: true
        type: string
      - description: src_amount
        in: query
        name: src_amount
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/payload.EstimateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/errors.Error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/errors.Error'
      summary: Estimate Uniswap V2 pool
      tags:
      - Estimate
swagger: "2.0"
